### ISSUE TITLE
Additional # in code block makes sample invalid

### ISSUE THREAD

**Issue by rbouqueau** [gpac/wiki#18]
See `##begin mixed.m3u` in https://wiki.gpac.io/Howtos/playlist/ which displays `###begin mixed.m3u`.

**Comment by jeanlf** [comment]
hmm that's bad indeed. @PierreDillard could you have a look ?

**Comment by PierreDillard** [comment]
Hi  @jeanlf and @nlsdvl 
I’ve created a fix for this issue in [PR #24](https://github.com/gpac/wiki/pull/24). It now ignores `#` within code blocks to prevent unwanted changes. Please take a look!
