### ISSUE TITLE
"Was this page helpful?" dialog does not disappear

### ISSUE THREAD

**Issue by DenizUgur** [gpac/wiki#27]
When you give feedback to the "Was this page helpful?" dialog, it doesn't go away and prevents user from accessing the end of sidebar.

**Comment by PierreDillard** [comment]
Hello @DenizUgur,  

Thank you for reporting this issue!  

Regarding the "feedback" dialog, it’s currently designed to remain visible after feedback submission, consistent with previous versions. That said, I agree that the user experience could be improved by making the widget disappear after feedback is given.

As for the issue of not being able to scroll to the end of the sidebar, I haven’t encountered this in my tests, even on content-heavy pages like [this one](https://wiki.gpac.io/Filters/avmix/#options). Could you provide more details to help me investigate further? Specifically:  
- On which page(s) does this occur?  
- What operating system and browser are you using?

**Comment by DenizUgur** [comment]
Hi @PierreDillard,

Consider the "General Filters Concept" page on a desktop browser. Before or after you provide a feedback the dialog will remain there. Therefore you won't be able to click the items at the end of the sidebar. The widget would overlay the sidebar.

If the dialog is required to be visible/accessible, it can be minimized with only the feedback selection the user made. For example, if I selected this page is useful then a green happy face at the bottom right corner makes sense. Or just disappear altogether.

**Comment by PierreDillard** [comment]
@DenizUgur,  

Thank you for the clarification and your suggestions!  
I’m currently working on a solution to address the dialog issue that affects access to the sidebar, and I’ll keep you updated on my progress.
